name: Clair Scan

on:
  workflow_dispatch:
    inputs:
       image:
         description: 'Container Image'
         default: "vulnerables/web-dvwa:latest"
         required: true
       updater:
         description: 'Clair updater type'
         default: "debian"
         required: true
jobs:  
  clair-scan:
    name: Scan image with Clair
    runs-on: ubuntu-latest
    steps:
    - name: Pull image to local registry
      run: docker pull vulnerables/web-dvwa:latest
    - name: Clair Test
      id: clairtest
      uses: santander-group/clair-scan-action@update-action
      with:
       image: "vulnerables/web-dvwa:latest"
       report_format: xml
       updater: debian
       report_path: clair-report.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: clair-result
        path: clair-report.xml
